[package]
authors = ["Fabricio <fabricio7p@protonmail.com>"]
categories = ["command-line-utilities", "text-processing"]
description = "Cli application for Gistit"
edition = "2021"
keywords = ["code", "snippets", "share", "hash"]
license = "../LICENSE"
name = "gistit"
readme = "README.md"
repository = "https://github.com/gistit.git"
version = "0.1.0"

[features]
default = ["clipboard"]
clipboard = ["which", "base64"]

[dependencies]
env_logger = { version = "0.9.0", default-features = false, features = ["termcolor", "atty"] }
argh = "0.1.6"
async-trait = "0.1.51"
lazy_static = "1.4.0"
log = "0.4.14"
phf = { version = "0.10", features = ["macros"] }
ngrammatic = "0.3.2"
rust-crypto = "0.2.36"
rand = "0.8.4"
colored = "2.0.0"
which = { version = "4.2.2", optional = true }
base64 = { version = "0.13.0", optional = true }

[dependencies.tokio]
features = ["macros", "fs", "net", "rt", "rt-multi-thread", "sync", "io-util"]
version = "1.12.0"

[profile.release]
lto = true
