[package]
authors = ["Fabricio <fabricio7p@protonmail.com>"]
categories = ["command-line-utilities", "text-processing"]
description = "Cli application for Gistit"
edition = "2018"
keywords = ["code", "snippets", "share", "hash"]
name = "gistit"
readme = "README.md"
repository = "https://github.com/gistit.git"
version = "0.1.0"
license = "../LICENSE"

[dependencies]
argh = "0.1.6"
# tokio = { version = "1", features = ["rt", "net", "rt-multi-thread", "macros"] }
