[package]
authors = ["Fabricio <fabricio7p@protonmail.com>"]
categories = ["command-line-utilities", "text-processing"]
description = "Gistit daemon used for p2p file sharing"
edition = "2021"
keywords = ["code", "snippets", "share", "hash"]
license = "MIT or Apache-2.0"
name = "gistit-daemon"
repository = "https://github.com/fabricio7p/gistit"
version = "0.1.0"

[dependencies]
async-trait = "0.1.52"
base64 = "0.13.0"
directories = "4.0.1"
lib-gistit = { path = "../lib-gistit/" }

[dependencies.clap]
version = "3.0.7"
features = ["cargo"]

[dependencies.tokio]
features = ["macros", "fs", "rt", "rt-multi-thread", "sync", "io-util"]
version = "1.15.0"

[dependencies.libp2p]
version = "0.41.1"
default-features = false
features = ["noise", "kad", "identify", "mdns", "mplex", "tcp-async-io", "dns-async-std", "websocket", "yamux", "request-response"]

