[package]
name = "gistit-ipc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/fabricio7p/gistit"
publish = false

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.136", features = ["derive"] }
