[package]
name = "gistit-ipc"
authors = ["Fabricio <fabricio7p@protonmail.com>"]
description = "Inter process communication for gistit-cli and gistit-daemon"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/fabricio7p/gistit"
readme = "./README"
version = "0.1.0"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.136", features = ["derive"] }
